In [ ]:
#第五章pandas入门
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

In [8]:
#Series是一组数据与之相关的数据标签（即索引）组成。
obj=pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
np.exp(obj)

0      54.598150
1    1096.633158
2       0.006738
3      20.085537
dtype: float64

In [10]:
#设置带有标记的索引
obj2=pd.Series([4,7,-4,3],index=['d','c','b','a'])
obj2

d    4
c    7
b   -4
a    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'c', 'b', 'a'], dtype='object')

In [12]:
obj2['a']

3

In [13]:
obj2['d']=6

In [14]:
obj2

d    6
c    7
b   -4
a    3
dtype: int64

In [15]:
#进行运算
obj2[obj2>0]

d    6
c    7
a    3
dtype: int64

In [11]:
obj2*2

d    12
c    14
b    -8
a     6
dtype: int64

In [16]:
np.exp(obj2)

d     403.428793
c    1096.633158
b       0.018316
a      20.085537
dtype: float64

In [17]:
#将它看成是字典
'b' in obj2

True

In [18]:
'e' in obj2

False

In [17]:
#如果数据存放在字典中，可以用这个字典创建Series
sdata={'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3=pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
states=['California','Ohio','Oregon','Texas']
obj4=pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
#NaN(即‘非数字’，not a number)在pandas中，它表示缺失或Na值
#用isnull和notnull函数检测缺失数据
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [21]:
#序列也有类似的方法
obj.isnull()

0    False
1    False
2    False
3    False
dtype: bool

In [22]:
#Series对象本身及其索引都有一个name属性。
obj4.name='population'
obj4.index.name='state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [23]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [24]:
obj.index=['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [26]:
#创建DataFrame
data={'state':['Ohio','Ohio','Nevada','Nevada','Nevada'],
     'year':[2000,2001,2002,2002,2003],
     'pop':[1.5,1.7,3.6,2.4,2.9]}
frame=pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2  Nevada  2002  3.6
3  Nevada  2002  2.4
4  Nevada  2003  2.9

In [27]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2  Nevada  2002  3.6
3  Nevada  2002  2.4
4  Nevada  2003  2.9

In [28]:
pd.DataFrame(data,columns=['year','state','pop'])


year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002  Nevada  3.6
3  2002  Nevada  2.4
4  2003  Nevada  2.9

In [30]:
#从frame中获取一个Series
frame['state']

0      Ohio
1      Ohio
2    Nevada
3    Nevada
4    Nevada
Name: state, dtype: object

In [31]:
frame.year

0    2000
1    2001
2    2002
3    2002
4    2003
Name: year, dtype: int64

In [34]:
#通过行获取
frame.loc[2]

state    Nevada
year       2002
pop         3.6
Name: 2, dtype: object

In [36]:
frame['eastern']=frame.state=='Ohio'
frame

state  year  pop  eastern
0    Ohio  2000  1.5     True
1    Ohio  2001  1.7     True
2  Nevada  2002  3.6    False
3  Nevada  2002  2.4    False
4  Nevada  2003  2.9    False

In [40]:
#del frame['eastern']
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [41]:
frame.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Nevada', 2002, 3.6],
       ['Nevada', 2002, 2.4],
       ['Nevada', 2003, 2.9]], dtype=object)

In [42]:
#索引对象
obj=pd.Series(range(3),index=['a','b','c'])
index=obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [43]:
#索引对象不可变
labels=pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [46]:
obj2=pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [48]:
obj2.index is labels

True

In [49]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2  Nevada  2002  3.6
3  Nevada  2002  2.4
4  Nevada  2003  2.9

In [50]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [51]:
'Ohio' in frame.columns

False

In [52]:
2000 in frame.index

False

In [53]:
dup_labels=pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [54]:
#5.2基本功能
obj =pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [56]:
#用Series的reindex将会重新排序
obj2=obj.reindex(['a','b','c','d'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [57]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [58]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [59]:
#借助DataFrame，reindex可以修改（行）索引和列。只传递一个序列时，会重新索引结果的行
frame=pd.DataFrame(np.arange(9).reshape(3,3),index=['a','c','d']
                   ,columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [62]:
frame2=frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [64]:
#列可以用columns关键字重新索引
states=['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [66]:
#丢弃指定轴上的项,使用drop方法
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [67]:
new_obj=obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [68]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [70]:
#删除任意轴上的索引
data=pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorado','Utah','NewYork'],
                 columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [71]:
#用标签序列调用drop从行标签（axis 0）删除值
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah       8    9     10    11
NewYork   12   13     14    15

In [72]:
#通过传递axis=1或axis=‘columns’可以删除列的值
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
NewYork    12     14    15

In [73]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
NewYork    12     14

In [76]:
#索引、选取和过滤
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [77]:
obj['b']

1.0

In [78]:
obj[0]

0.0

In [79]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [80]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [81]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [82]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [83]:
#利用标签的切片运算与普通的Python切片运算不同，其末端是包含的
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [85]:
#用切片可以对Series的相应部分进行设置
obj['b':'c']=5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [86]:
#用一个值或序列对DataFrame进行索引其实就是获取一个或多个列
data=pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorado','Utah','New Tork'],
                 columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New Tork   12   13     14    15

In [87]:
data['two']

Ohio         1
Colorado     5
Utah         9
New Tork    13
Name: two, dtype: int32

In [88]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New Tork     14   12

In [89]:
#这种索引方式有几种特殊情况，首先通过切片或布尔型数组选取数据
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [90]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New Tork   12   13     14    15

In [91]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New Tork  False  False  False  False

In [93]:
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New Tork   12   13     14    15

In [94]:
#用loc（轴标签）和iloc（整数索引）进行选取
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [95]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [96]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [97]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [98]:
#这两个索引函数也适用于一个标签或多个标签的切片
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [99]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New Tork   12   13     14

In [100]:
#整数索引
ser=pd.Series(np.arange(3.0))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [101]:
#非整数索引
ser2=pd.Series(np.arange(3.),index=['a','b','c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [103]:
ser2[-2]

1.0

In [104]:
#为了进行统一，如果轴索引含有整数，数据选取会使用标签。为了更准确，请使用loc或iloc
ser[:1]

0    0.0
dtype: float64

In [105]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [106]:
ser.iloc[:1]

0    0.0
dtype: float64

In [110]:
#算术运算和数据对齐
s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','b','c','d'])
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
s1

a    7.3
b   -2.5
c    3.4
d    1.5
dtype: float64

In [111]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [112]:
s1+s2

a    5.2
b    NaN
c    7.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [114]:
df1=pd.DataFrame(np.arange(9.0).reshape(3,3),index=['Ohio','Texas','Colorado'],columns=list('bcd'))
df2=pd.DataFrame(np.arange(12.).reshape(4,3),index=['Utha','Ohio','Texas','Oregon'],columns=list('bde'))

In [115]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [116]:
df2

b     d     e
Utha    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [117]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utha      NaN NaN   NaN NaN

In [119]:
df1=pd.DataFrame({'A':[1,2]})
df2=pd.DataFrame({'B':[3,4]})
df1

A
0  1
1  2

In [120]:
df2

B
0  3
1  4

df1-df2

In [121]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [124]:
#在算术方法中填充值
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [126]:
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [127]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [128]:
#使用df1的add方法，传入df2以及一个fill_value参数
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [129]:
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [130]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [131]:
#DataFrame和Seires之间的运算
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [132]:
arr[0]

array([0., 1., 2., 3.])

In [133]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])